apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-arjh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ejpg-tenant/status-quarkus-io/statusquarkusio-arjh@sha256:a550132190d67746ab41ab43a7116bb0f755ffa9a4d2123a7b05cb7f66ddac15
        name: my-java-quarkus
        resources: {}
status: {}
