apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-arjh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-arjh
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-arjh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-arjh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-arjh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ejpg-tenant/status-quarkus-io/statusquarkusio-arjh@sha256:a550132190d67746ab41ab43a7116bb0f755ffa9a4d2123a7b05cb7f66ddac15
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
